using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSUPaymentService.Model
{
    public class PaymentResult
    {
        /// <summary>
        /// The resultCode. The possible values are: Unknown, FailedCardNo, FailedMonth, FailedYear, FailedSecurityCode, Success
        /// </summary>
        public string ResultCode { get; set; }
        /// <summary>
        /// This is the result message. A further description in case of an error
        /// </summary>
        public string ResultMessage { get; set; }
        /// <summary>
        /// This is the transaction id generated by the payment service. Is only available if the transaction is successful.
        /// </summary>
        public string TransactionId { get; set; }
        /// <summary>
        /// This is the order id provided by the payment, this ensures traceability with the transaction id.
        /// </summary>
        public int OrderId { get; set; }
    }
    public enum PaymentCode
    {
        Unknown = 0,
        FailedCardNo,
        FailedMonth,
        FailedYear,
        FailedSecurityCode,
        Success
    }
}
